server:
  port: 8889
spring:

  application:
    name: GATEWAY-SERVICE
  cloud:
    consul:
      host: ${SPRING_CLOUD_CONSUL_HOST:localhost}
      port: ${SPRING_CLOUD_CONSUL_PORT:8500}
      discovery: SERVICE-CLIENT

